apiVersion: v1
kind: Secret
metadata:
  name: openpanel-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: openpanel
    component: secrets
type: Opaque
stringData:
  # Cookie secret
  COOKIE_SECRET: {{ .Values.secrets.cookieSecret | quote }}

  # PostgreSQL connection strings
{{- if .Values.postgresql.enabled }}
  DATABASE_URL: "postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.service.name }}:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.database }}?schema=public"
  DATABASE_URL_DIRECT: "postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.service.name }}:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.database }}?schema=public"
{{- else }}
  DATABASE_URL: "postgresql://{{ .Values.externalPostgresql.user }}:{{ .Values.externalPostgresql.password }}@{{ .Values.externalPostgresql.host }}:{{ .Values.externalPostgresql.port }}/{{ .Values.externalPostgresql.database }}?schema={{ .Values.externalPostgresql.schema }}"
  DATABASE_URL_DIRECT: "postgresql://{{ .Values.externalPostgresql.user }}:{{ .Values.externalPostgresql.password }}@{{ .Values.externalPostgresql.host }}:{{ .Values.externalPostgresql.port }}/{{ .Values.externalPostgresql.database }}?schema={{ .Values.externalPostgresql.schema }}"
{{- end }}

  # Redis connection string
{{- if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ .Values.redis.service.name }}:{{ .Values.redis.service.port }}"
{{- else }}
  REDIS_URL: "redis://{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}"
{{- end }}

  # ClickHouse connection string
{{- if .Values.clickhouse.enabled }}
  CLICKHOUSE_URL: "http://{{ .Values.clickhouse.service.name }}:{{ .Values.clickhouse.service.httpPort }}/{{ .Values.clickhouse.database }}"
{{- else }}
  CLICKHOUSE_URL: "http://{{ .Values.externalClickhouse.host }}:{{ .Values.externalClickhouse.port }}/{{ .Values.externalClickhouse.database }}"
{{- end }}

  # Optional: Email configuration
{{- if .Values.secrets.resendApiKey }}
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | quote }}
{{- end }}
{{- if .Values.secrets.emailSender }}
  EMAIL_SENDER: {{ .Values.secrets.emailSender | quote }}
{{- end }}

  # Optional: AI features
{{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
{{- end }}
{{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
{{- end }}

  # Optional: Google OAuth
{{- if .Values.secrets.googleClientId }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
{{- end }}
{{- if .Values.secrets.googleClientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
{{- end }}
